### ISSUE TITLE
Should understand passwords in Zoom URL

### ISSUE THREAD

**Issue by taavo** [flavorjones/calendar-assistant#154]
Some Zoom URLs have passwords in them, in apparently the following format: 
`https://{{company}}.zoom.us/j/{{room id}}?pwd={{ probably some kind of hash? }}`

`calendar-assistant join` sadly strips this password information out, which means you can't get into your Zoom. It would be better if calendar-assistant retained this password parameter.

Thanks!

**Comment by flavorjones** [comment]
I'll take a look.

**Comment by flavorjones** [comment]
See PR #155

**Comment by flavorjones** [comment]
v0.12.0 has been released with this feature!
