### ISSUE TITLE
Specify a default profile

### ISSUE THREAD

**Issue by gsiener** [flavorjones/calendar-assistant#22]
I find myself almost always using one profile, and I think the commands would flow more easily without needing to add the profile.  E.g.:

```calendar-assistant show work``` vs. ```calendar-assistant show```
```calendar-assistant location-set work WFH today``` vs. ```calendar-assistant location-set WFH today```

I'd suggest calendar-assistant profile-set work, which would then allow subsequent commands to default to that profile.  WDYT?

**Comment by flavorjones** [comment]
Here's how I'd like to break this story down:

- [ ] store auth tokens in a config file
- [ ] store a "default" profile preference in that same config file
- [ ] allow choosing the active profile via a CLI flag
- [ ] allow choosing *all* profiles via a CLI flag (I personally would use this for `location-set`)

**Comment by flavorjones** [comment]
@gsiener @mikfreedman note that when you pull this change down, the local "tokens.yml" file won't be used anymore, you'll need to re-auth and tokens will be stored in `~/.calendar-assistant`

(or you can manually import them into that file if you like)

**Comment by flavorjones** [comment]
@gsiener @mikfreedman note that now you should not provide the profile name if you wish to use the default. If you wish to change the default, edit `~/.calendar-assistant`. If you wish to specify the a non-default profile, use `--profile PROFILE_NAME` or `-p PROFILE_NAME`.
