### ISSUE TITLE
generate a list of upcoming availability

### ISSUE THREAD

**Issue by gsiener** [flavorjones/calendar-assistant#23]
When I'm trying to schedule a meeting with someone outside the org, I often provide a list of upcoming  available slots.  Ultimately, I'd love to have [Sunrise Meet](http://blog.sunrise.am/post/118691977104/introducing-meet-the-fastest-way-to-schedule-a) back.  In the short term, my suggestion would be something like:

```
$ calendar-assistant show availability work [--size 60min]

Monday (10/8) 2pm-3:30pm
Tuesday (10/9) 11am-12pm
Wednesday (10/10) 4pm-6pm
```

**Comment by flavorjones** [comment]
I have a WIP:

```
$ ruby -Ilib bin/calendar-assistant avail today..tomorrow
Availability on Monday, October 15 (all times America/New_York):
	• 9:20am - 11:00am
	• 11:30am - 12:30pm
	• 1:30pm - 6:00pm

Availability on Tuesday, October 16 (all times America/New_York):
	• 7:20am - 9:00am
	• 11:00am - 12:00pm
	• 1:00pm - 6:00pm
```

**Comment by flavorjones** [comment]
better wip:

---

<pre><i>mdalessio@pivotal.io (all times in America/New_York)</i>

<b>Availability on Monday, October 22:</b>

 • 7:25am - 9:00am
 • 9:25am - 10:30am
 • 11:30am - 12:30pm
 • 3:25pm - 4:30pm
 • 5:30pm - 6:00pm


</pre>

**Comment by flavorjones** [comment]
Done. See README for details.
