### ISSUE TITLE
Can't do anything but help after authorization

### ISSUE THREAD

**Issue by infews** [flavorjones/calendar-assistant#28]
```
15:05:30 firecrest in ~/workspace/calendar-assistant
✓ master → ruby -Ilib bin/calendar-assistant show today
ERROR: could not parse /Users/dwfrank/.calendar-assistant: undefined method `ascii_tree' for nil:NilClass
```

Is this an authorization fail? Or PEBKAC?

**Comment by flavorjones** [comment]
I've tried, but can't reproduce this. If you just want to get up and going, delete `~/.calendar-assistant` and re-authorize.

**Comment by flavorjones** [comment]
Going to close this. Feel free to comment if you're still having trouble and I'll reopen and we can dig in.
