### ISSUE TITLE
"availability" command should support multiple users

### ISSUE THREAD

**Issue by flavorjones** [flavorjones/calendar-assistant#46]
hanging off #18 

---

I'm imagining a workflow like:

__Given__ somebody@gmail.com whose home time zone is America/Los_Angeles ...

<pre>
<b>$</b> calendar-assistant avail -r me,somebody@gmail.com

<i>mike.dalessio@gmail.com, somebody@gmail.com</i>
<i>- looking for blocks at least 30 mins long</i>
<i>- between 9am and 6pm in America/New_York</i>
<i>- between 9am and 6pm in America/Los_Angeles</i>

<b>Availability on Monday, November 19:</b>

 • 12:00pm -  1:00pm EST /  9:00am - 10:00am PST <i>(1h)</i>
 •  1:30pm -  2:00pm EST / 10:30am - 11:00am PST <i>(30m)</i>

</pre>

The alternative UX would be repeating usage of params:

```
calendar-assistant avail -r me -r somebody@gmail.com
```

which is something that Thor doesn't support (it instead prefers passing multiple space-delimited options like `-r me somebody@gmail.com` which I find confusing and I'm pretty sure isn't POSIX-compliant :man_shrugging:).

I'm open to other ideas here. @gsiener @mikfreedman

**Comment by gsiener** [comment]
I like the idea of separating people by a delimiter.  If a comma works, sgtm

**Comment by flavorjones** [comment]
#48 is the related PR that's ready for review (and still has a couple of warts)

**Comment by flavorjones** [comment]
I've merged #48 manually

But a few things that still need tweaking:

* checking availability against a colleague in Toronto when I'm in NYC is weird:

<pre><i>- between 8am and 6pm in America/New_York</i>
<i>- between 8am and 6pm in America/Toronto</i>

<b>Availability on Monday, November 19:</b>

 •  9:25am - 12:30pm EST /  9:25am - 12:30pm EST<i> (3h 5m)</i>
 •  1:30pm -  4:30pm EST /  1:30pm -  4:30pm EST<i> (3h)</i>
 •  5:00pm -  6:00pm EST /  5:00pm -  6:00pm EST<i> (1h)</i>
</pre>

* checking availability against a colleague in an _earlier_ time zone bring in an extra day:

<pre><font color="#729FCF"><b>$ </b></font>be ruby -Ilib bin/calendar-assistant avail -a redacted@pivotal.io 2018-11-19..2018-11-20
<i>redacted@pivotal.io</i>
<i>- looking for blocks at least 30 mins long</i>
<i>- between 9am and 6pm in Europe/London</i>

<b>Availability on Monday, November 19:</b>

 • 11:30am - 12:00pm GMT<i> (30m)</i>
 • 12:25pm -  1:30pm GMT<i> (1h 5m)</i>
 •  1:45pm -  2:30pm GMT<i> (45m)</i>
 •  3:20pm -  4:30pm GMT<i> (1h 10m)</i>

<b>Availability on Tuesday, November 20:</b>

 •  9:15am -  9:45am GMT<i> (30m)</i>
 • 10:30am - 11:00am GMT<i> (30m)</i>
 • 11:25am -  2:00pm GMT<i> (2h 35m)</i>

<b>Availability on Wednesday, November 21:</b>

 •  9:00am -  6:00pm GMT<i> (9h)</i>

</pre>

**Comment by flavorjones** [comment]
addressed those two issues in 6c139c4 and e22c97a
