### ISSUE TITLE
EventRepository: Replace magic number for HTTP Status Code on ClientError

### ISSUE THREAD

**Issue by mikfreedman** [flavorjones/calendar-assistant#64]
This magic number:

https://github.com/flavorjones/calendar-assistant/blob/8b2c3b1df745706e7ff46fb7d7ba561562e2fe4e/lib/calendar_assistant/event_repository.rb#L10

Should probably be replaced with a constant.

**Comment by flavorjones** [comment]
See https://www.rubydoc.info/stdlib/net/Net/HTTPResponse

I think what we want is `Net::HTTPNotFound`

**Comment by flavorjones** [comment]
ALSO: SO NITPICKY :rofl:

**Comment by mikfreedman** [comment]
Ya, I remembered during the night that I had cheated on my last story and wanted a reminder for myself rather than fix it during work hours! Also, I thought @flavorjones you'd appreciate the nitpickiness

**Comment by mikfreedman** [comment]
This is actually weirdly harder than it should be.
