### ISSUE TITLE
Apply predicates to events

### ISSUE THREAD

**Issue by mikfreedman** [flavorjones/calendar-assistant#72]
As a user I want to be able to filter events for the following commands:

* avail
* join
* lint
* location
* show

and I want the following predicates to be made available:

 * location_event
 * all_day
 * past
 * current
 * future
 * accepted
 * declined
 * awaiting
 * tentative
 * self
 * one_on_one
 * busy
 * commitment
 * private
 * public
 * explicitly_visible
 * recurring
 * abandoned
 * visible_guestlist

**Comment by flavorjones** [comment]
I'll note that this feature would supersede/deprecate the `-c` option on the `show` command. Which is a good thing.

**Comment by flavorjones** [comment]
During implementing this, I would like to encourage us to make the list of predicates programmatically discoverable; I'm thinking of how this functionality might be exposed in a web UI for example.

**Comment by mikfreedman** [comment]
Here’s what I was thinking, an array constant the contains the predicate
methoda, and a test that fails should there be a :method? Method not in the
list, that way we keep some meta-programming out of the production code.
