### ISSUE TITLE
Move chat to public slack/gitter

### ISSUE THREAD

**Issue by mikfreedman** [flavorjones/calendar-assistant#78]
We should think about unpicking our connection to private communications for this project

**Comment by mikfreedman** [comment]
@gsiener @flavorjones ^^

**Comment by flavorjones** [comment]
I actually looked into this a little bit ago to try to find a better home for Nokogiri.

Gitter's github integration unfortunately relies on a Github Service, and Github is still planning on [turning off Services on Jan 31, 2019](https://developer.github.com/v3/guides/replacing-github-services/). It doesn't appear to have a replacement [Github App](https://github.com/marketplace?utf8=%E2%9C%93&query=gitter). In fact in the entire category of "chat", [only Slack has an app](https://github.com/marketplace/category/chat). I don't know what Gitter's plans are post-service-shutdown.

Public slack is an interesting idea, but I don't want to set up a whole new Slack instance (and set up the app to allow people to self-register) just for Calendar Assistant. Is there an existing public slack on which we can create a channel? Preferably focused on OSS projects?

A few options I'm aware of:

The [Ruby on Rails slack](https://rubyonrails-link.slack.com/) which is popular and high traffic but doesn't allow anybody to create a channel.

There's also the [Ruby Developers slack](https://rubydevelopers.slack.com/archives/C037LESDF/p1548117455086500?thread_ts=1548065711.083700&cid=C037LESDF), which is pretty low-traffic but appears to allow people to create channels.

There's a [NYC Devs slack](https://nycdevs.slack.com/archives/C0CCUFDK3/p1548004093017600), which also doesn't allow creation of new channels.

Maybe we should try the Ruby Developers slack?

**Comment by gsiener** [comment]
I’m game to try the ruby developers slack.  Does that allow you to set up integrations (like w GitHub)?

**Comment by flavorjones** [comment]
The Ruby Developers slack only allows creation of private rooms ... and limited integrations.

**Comment by flavorjones** [comment]
I've set up a Gitter here:

> https://gitter.im/calendar-assistant/community#

and attempted to manually configure Github integration via webhook. We'll see how it goes.

**Comment by flavorjones** [comment]
To integrate with Concourse we'll need to write a resource and send a PR to gitter, something similar to https://gitlab.com/gitlab-org/gitter/services/tree/master/lib/circleci

**Comment by flavorjones** [comment]
Done, see 40ed531 which integrates the newly-written https://github.com/flavorjones/webhook-notification-resource

**Comment by flavorjones** [comment]
Oh - and the gitter room is https://gitter.im/flavorjones/calendar-assistant
